// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "Text Box":return img`
..............................
........11111111111111........
.....11111ffffffffff11111.....
....1111111111111111111111....
....111ffffffffffffffff111....
...11ffffffffffffffffffff11...
...11ffffffffffffffffffff11...
..111ffffffffffffffffffff111..
.11ff11ffffffffffffffff11ff11.
.11ffffffffffffffffffffffff11.
.11ffffffffffffffffffffffff11.
.11ffffffffffffffffffffffff11.
.11ffffffffffffffffffffffff11.
.11ffffffffffffffffffffffff11.
.11ffffffffffffffffffffffff11.
.11ffffffffffffffffffffffff11.
.11ffffffffffffffffffffffff11.
.11ffffffffffffffffffffffff11.
.11ffffffffffffffffffffffff11.
.11ffffffffffffffffffffffff11.
.11ffffffffffffffffffffffff11.
.11ff11ffffffffffffffff11ff11.
..111ffffffffffffffffffff111..
...11ffffffffffffffffffff11...
...11ffffffffffffffffffff11...
....111ffffffffffffffff111....
....1111111111111111111111....
.....11111ffffffffff11111.....
........11111111111111........
..............................
`;
            case "image1":
            case "Player":return img`
..............................
..............................
..............................
..............................
............ffffff............
...........fdeeeeef...........
..........fdddeeeeef..........
..........fedddedeef..........
..........feeeeeeeff..........
..........fffefeef1f..........
..........f1dfdffd1f..........
..........f1dddddd1f..........
...........f1dddd1f...........
............ffffff............
..........fff4e4efff..........
.........fe4e4ffe4e4f.........
........f4e4e4e4e4e4ef........
........f4efe4e4e4f4ef........
........f4efe4e4e4f4ef........
........f4efe4e4e4f4ef........
........ffffe4e4e4ffff........
........f1dffffffffd1f........
.........fffbcffcbfff.........
...........fbcffcbf...........
...........fbcffcbf...........
...........fbcffcbf...........
..........ffffffffff..........
.........f11dbffbd11f.........
........fdddbf..fbdddf........
.........ffff...fffff.........
`;
            case "image3":
            case "Map Asset":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . d 1 1 1 1 1 1 . . . . . . . 
. . . d 1 . . . d 1 . . . . . . 
. . . d 1 . . . d 1 . . . . . . 
. . . d 1 . . d 1 . . . . . . . 
. . . d 1 1 1 1 . . . . . . . . 
. . . d 1 . . d 1 . . . . . . . 
. . . d 1 . . . d 1 . . . . . . 
. . . d 1 . . . d 1 . . . . . . 
. . d 1 1 1 1 1 1 . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
